---
name: Release Development Image to Github Registry

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/release-dev-image.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-security-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define Image Tag
        id: define-image-tag
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          BRANCH_NAME="${BRANCH_NAME#docker/}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          echo "tag_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ steps.define-image-tag.outputs.tag_name }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: development
          platforms: ${{ matrix.platform }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args: |
            APP_VER=${{ steps.define-image-tag.outputs.tag_name }}
            RAILS_ENV=development
            NODE_ENV=development

      - name: Run security checks
        uses: aquasecurity/trivy-action@0.0.19
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: table

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${{ steps.meta.outputs.tags }}
