---
name: Release Development Image to Github Registry

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - Dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-security-check:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    timeout-minutes: 300
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define Image Tag
        id: define-image-tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/docker/}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          echo "tag_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ steps.define-image-tag.outputs.tag_name }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: development
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args: |
            APP_VER=${{ steps.meta.outputs.tag_name }}
            RAILS_ENV=development
            NODE_ENV=development

  push-to-registry:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    needs: build-and-security-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to Github Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: development
          push: false
          tags: ${{ needs.build-and-security-check.outputs.tag_name }}
          labels: ${{ needs.build-and-security-check.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
